$MODALIAS=.*	root:root	0660	@modprobe -q -b "$MODALIAS"

# load frambuffer console when first frambuffer is found
fb0	root:root 0660 @modprobe -q -b fbcon

# ram.*
ram([0-9]*)	root:root 0660 >rd/%1
loop([0-9]+)	root:root 0660 >loop/%1

# persistent storage
dasd.*		root:root 0660 */lib/mdev/persistent-storage
mmcblk.*	root:root 0660 */lib/mdev/persistent-storage
nbd.*		root:root 0660 */lib/mdev/persistent-storage
nvme.*		root:root 0660 */lib/mdev/persistent-storage
sd[a-z].*	root:root 0660 */lib/mdev/persistent-storage
sr[0-9]+	root:root 0660 */lib/mdev/persistent-storage
vd[a-z].*	root:root 0660 */lib/mdev/persistent-storage
xvd[a-z].*	root:root 0660 */lib/mdev/persistent-storage

ttyACM[0-9]	root:root 0660 @ln -sf $MDEV modem
ttyUSB[0-9]	root:root 0660 @ln -sf $MDEV modem
ttyLTM[0-9]	root:root 0660 @ln -sf $MDEV modem
ttySHSF[0-9]	root:root 0660 @ln -sf $MDEV modem
slamr		root:root 0660 @ln -sf $MDEV slamr0
slusb		root:root 0660 @ln -sf $MDEV slusb0

# dri device
card[0-9]	root:root 0660 =dri/

# alsa sound devices and audio stuff
pcm.*		root:root 0660	=snd/
control.*	root:root 0660	=snd/
midi.*		root:root 0660	=snd/
seq		root:root 0660	=snd/
timer		root:root 0660	=snd/

adsp		root:root 0660 >sound/
audio		root:root 0660 >sound/
dsp		root:root 0660 >sound/
mixer		root:root 0660 >sound/
sequencer.*	root:root 0660 >sound/

# PTP devices
ptp[0-9]	root:root 0660 */lib/mdev/ptpdev

# virtio-ports
SUBSYSTEM=virtio-ports;vport.* root:root 0600 @mkdir -p virtio-ports; ln -sf ../$MDEV virtio-ports/$(cat /sys/class/virtio-ports/$MDEV/name)

# misc stuff
agpgart		root:root 0660  >misc/
psaux		root:root 0660  >misc/
rtc		root:root 0664  >misc/

# v4l stuff
vbi[0-9]	root:root 0660 >v4l/
video[0-9]+	root:root 0660 >v4l/
media[0-9]+	root:root 0660 >v4l/

# dvb stuff
dvb.*		root:root 0660 */lib/mdev/dvbdev

# load drivers for usb devices
usb[0-9]+	root:root 0660 */lib/mdev/usbdev

# zaptel devices
zap(.*)		root:root 0660 =zap/%1

# fallback for any!device -> any/device
(.*)!(.*)	root:root 0660 =%1/%2
